
package com.oracle.physician.service.delegate.stub.jaxws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PatientFacade", targetNamespace = "http://www.oracle.com/medrec")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PatientFacade {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.oracle.physician.service.delegate.stub.jaxws.FoundPatient>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fuzzyFindApprovedPatientsByLastnameAndSsn", targetNamespace = "http://www.oracle.com/medrec", className = "com.oracle.physician.service.delegate.stub.jaxws.FuzzyFindApprovedPatientsByLastnameAndSsn")
    @ResponseWrapper(localName = "fuzzyFindApprovedPatientsByLastnameAndSsnResponse", targetNamespace = "http://www.oracle.com/medrec", className = "com.oracle.physician.service.delegate.stub.jaxws.FuzzyFindApprovedPatientsByLastnameAndSsnResponse")
    @Action(input = "http://www.oracle.com/medrec/PatientFacade/fuzzyFindApprovedPatientsByLastnameAndSsnRequest", output = "http://www.oracle.com/medrec/PatientFacade/fuzzyFindApprovedPatientsByLastnameAndSsnResponse")
    public List<FoundPatient> fuzzyFindApprovedPatientsByLastnameAndSsn(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "setRecordFacade", targetNamespace = "http://www.oracle.com/medrec", className = "com.oracle.physician.service.delegate.stub.jaxws.SetRecordFacade")
    @ResponseWrapper(localName = "setRecordFacadeResponse", targetNamespace = "http://www.oracle.com/medrec", className = "com.oracle.physician.service.delegate.stub.jaxws.SetRecordFacadeResponse")
    @Action(input = "http://www.oracle.com/medrec/PatientFacade/setRecordFacadeRequest", output = "http://www.oracle.com/medrec/PatientFacade/setRecordFacadeResponse")
    public void setRecordFacade();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.oracle.physician.service.delegate.stub.jaxws.Patient
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatient", targetNamespace = "http://www.oracle.com/medrec", className = "com.oracle.physician.service.delegate.stub.jaxws.GetPatient")
    @ResponseWrapper(localName = "getPatientResponse", targetNamespace = "http://www.oracle.com/medrec", className = "com.oracle.physician.service.delegate.stub.jaxws.GetPatientResponse")
    @Action(input = "http://www.oracle.com/medrec/PatientFacade/getPatientRequest", output = "http://www.oracle.com/medrec/PatientFacade/getPatientResponse")
    public Patient getPatient(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.oracle.physician.service.delegate.stub.jaxws.FoundPatient
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findApprovedPatientBySsn", targetNamespace = "http://www.oracle.com/medrec", className = "com.oracle.physician.service.delegate.stub.jaxws.FindApprovedPatientBySsn")
    @ResponseWrapper(localName = "findApprovedPatientBySsnResponse", targetNamespace = "http://www.oracle.com/medrec", className = "com.oracle.physician.service.delegate.stub.jaxws.FindApprovedPatientBySsnResponse")
    @Action(input = "http://www.oracle.com/medrec/PatientFacade/findApprovedPatientBySsnRequest", output = "http://www.oracle.com/medrec/PatientFacade/findApprovedPatientBySsnResponse")
    public FoundPatient findApprovedPatientBySsn(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.oracle.physician.service.delegate.stub.jaxws.FoundPatient>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findApprovedPatientsByLastName", targetNamespace = "http://www.oracle.com/medrec", className = "com.oracle.physician.service.delegate.stub.jaxws.FindApprovedPatientsByLastName")
    @ResponseWrapper(localName = "findApprovedPatientsByLastNameResponse", targetNamespace = "http://www.oracle.com/medrec", className = "com.oracle.physician.service.delegate.stub.jaxws.FindApprovedPatientsByLastNameResponse")
    @Action(input = "http://www.oracle.com/medrec/PatientFacade/findApprovedPatientsByLastNameRequest", output = "http://www.oracle.com/medrec/PatientFacade/findApprovedPatientsByLastNameResponse")
    public List<FoundPatient> findApprovedPatientsByLastName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
